on:
  push:
    tags:        
      - 'v*'

name: Publish

jobs:
  tests:
    uses: ./.github/workflows/main.yml

  publish:
    name: Publish
    needs: [tests]
    runs-on: ubuntu-latest
    if: github.repository == 'jdrouet/tmdb-api'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}